<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Testng Cucumber Suite" duration-ms="2285" started-at="2020-12-07T14:15:44Z" finished-at="2020-12-07T14:15:46Z">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:main.CucumberRunner@343f4d3d]" name="feature" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Run All Tests" duration-ms="2285" started-at="2020-12-07T14:15:44Z" finished-at="2020-12-07T14:15:46Z">
      <class name="main.CucumberRunner">
        <test-method status="PASS" signature="setUp()[pri:0, instance:main.CucumberRunner@343f4d3d]" name="setUp" is-config="true" duration-ms="21" started-at="2020-12-07T19:45:44Z" finished-at="2020-12-07T19:45:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:main.CucumberRunner@343f4d3d]" name="setUpClass" is-config="true" duration-ms="213" started-at="2020-12-07T19:45:44Z" finished-at="2020-12-07T19:45:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:main.CucumberRunner@343f4d3d]" name="feature" duration-ms="1946" started-at="2020-12-07T19:45:44Z" description="Runs Cucumber Feature" data-provider="features" finished-at="2020-12-07T19:45:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Get Weather Details]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [200] but found [401]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AssertionError: expected [200] but found [401]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at org.testng.Assert.assertEquals(Assert.java:382)
	at stepMethods.APIStepMethods.launchAPI(APIStepMethods.java:21)
	at stepDefinition.APIStepDefinition.userLaunchesTheAPIWith(APIStepDefinition.java:13)
	at ?.Given user launches the API with "Kanpur"(Phase2.feature:5)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:main.CucumberRunner@343f4d3d]" name="tearDownClass" is-config="true" duration-ms="45" started-at="2020-12-07T19:45:46Z" finished-at="2020-12-07T19:45:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
        <test-method status="PASS" signature="quit()[pri:0, instance:main.CucumberRunner@343f4d3d]" name="quit" is-config="true" duration-ms="0" started-at="2020-12-07T19:45:47Z" finished-at="2020-12-07T19:45:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- main.CucumberRunner -->
    </test> <!-- Run All Tests -->
  </suite> <!-- Testng Cucumber Suite -->
</testng-results>
